version: 2.1

jobs:
  deploy:
    docker:
      - image: node:20
    steps:
      - checkout
      - run: npm install
      - run: npx trigger.dev@latest deploy

workflows:
  deploy-trigger:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
