version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.15

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "pnpm-lock.yaml" }}
            - node-modules-

      - run:
          name: Install dependencies
          command: npx pnpm@latest install --frozen-lockfile

      - save_cache:
          key: node-modules-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - run:
          name: Generate Prisma Client with deployment targets
          command: npx pnpm@latest prisma generate

      - run:
          name: 🚀 Deploy Trigger.dev
          command: |
            export TRIGGER_ACCESS_TOKEN="${TRIGGER_ACCESS_TOKEN}"
            export SKIP_ENV_VALIDATION=true
            export NODE_ENV=production
            echo "Deploying with SKIP_ENV_VALIDATION=true"
            npx trigger.dev@latest deploy

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
