version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.15

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: 🚀 Deploy Trigger.dev
          command: npx trigger.dev@latest deploy
          environment:
            TRIGGER_ACCESS_TOKEN: ${TRIGGER_ACCESS_TOKEN}

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
