version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.15

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Debug - Echo TRIGGER_ACCESS_TOKEN
          command: |
            echo "TRIGGER_ACCESS_TOKEN: ${TRIGGER_ACCESS_TOKEN}"
            echo "Token length: ${#TRIGGER_ACCESS_TOKEN}"
            echo "Token starts with: ${TRIGGER_ACCESS_TOKEN:0:10}..."

      - run:
          name: 🚀 Deploy Trigger.dev
          command: |
            export TRIGGER_ACCESS_TOKEN="${TRIGGER_ACCESS_TOKEN}"
            echo "Exported token starts with: ${TRIGGER_ACCESS_TOKEN:0:10}..."
            npx trigger.dev@latest deploy

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
