import {
  ArrowUpRight,
  InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  CheckIcon,
  ChevronUpIcon,
  CircleIcon,
  ArrowLeft,
  ArrowRight,
  XIcon,
  PanelLeftIcon,
  ChevronLeft,
  MinusIcon,
  GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  SquareTerminal,
} from "lucide-react";

export const Icons = {
  ArrowUpRight,
  Info: InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDown: ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  Check: CheckIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  ArrowLeft,
  ArrowRight,
  X: XIcon,
  PanelLeft: PanelLeftIcon,
  ChevronLeft,
  Minus: MinusIcon,
  GripVertical: GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  Terminal: SquareTerminal,
};

// Export individual icons for direct imports
export {
  ArrowUpRight,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronRight,
  MoreHorizontal,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  Bot,
  Database,
  MessageSquare,
  MessageCircle,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  Building,
};
