import {
  ArrowUpRight,
  InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  CheckIcon,
  ChevronUpIcon,
  CircleIcon,
  ArrowLeft,
  ArrowRight,
  XIcon,
  PanelLeftIcon,
  ChevronLeft,
  MinusIcon,
  GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  SquareTerminal,
  ChartSpline,
} from "lucide-react";
import { AiOutlineOpenAI } from "react-icons/ai";
import { FaXTwitter } from "react-icons/fa6";

// Create an Icons object that contains all icons
export const Icons = {
  ArrowUpRight,
  Info: InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDown: ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  Check: CheckIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  ArrowLeft,
  ArrowRight,
  X: XIcon,
  PanelLeft: PanelLeftIcon,
  ChevronLeft,
  Minus: MinusIcon,
  GripVertical: GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  Terminal: SquareTerminal,
  ChartSpline,
  OpenAI: AiOutlineOpenAI,
  XAI: FaXTwitter,
};

// Export individual icons for direct imports
export {
  ArrowUpRight,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronRight,
  MoreHorizontal,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  Bot,
  Database,
  MessageSquare,
  MessageCircle,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  Building,
  ChartSpline,
};

// Export the React Icons components
export { AiOutlineOpenAI as OpenAI };
export { FaXTwitter as XAI };
