import {
  ArrowUpRight,
  InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  CheckIcon,
  ChevronUpIcon,
  CircleIcon,
  ArrowLeft,
  ArrowRight,
  XIcon,
  PanelLeftIcon,
  ChevronLeft,
  MinusIcon,
  GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  SquareTerminal,
  ChartColumn,
  Loader2,
  SunMedium,
  Moon,
  Laptop,
  CreditCard,
  MoreVertical,
  Plus,
  HelpCircle,
  User,
  File,
  FileText,
  Image,
  Trash,
  Twitter,
  RefreshCw,
  BadgeCheck,
  ChevronsUpDown,
  LogOut,
  Sparkles,
  KeyRound,
  Bell,
  ExternalLinkIcon,
  CalendarIcon,
  XCircle,
  Settings2,
  Loader,
  Upload,
  CopyIcon,
  MailIcon,
  CheckCircle,
  RefreshCcw,
  FileUp,
  Download,
  Trash2,
  CheckCircle2,
  Filter,
  Sliders,
  EyeOff,
  ListFilter,
  Text,
  ArrowDownUp,
  ChevronsLeft,
  ChevronsRight,
  CircleDashed,
  CircleOff,
  ArrowUp,
  ArrowDown,
} from "lucide-react";
import { AiOutlineOpenAI } from "react-icons/ai";
import {
  PiFileTxt,
  PiFilePdf,
  PiFileDoc,
  PiFileXls,
  PiFilePpt,
} from "react-icons/pi";
import { FaXTwitter } from "react-icons/fa6";
import { SiGooglecalendar } from "react-icons/si";
import { TiContacts } from "react-icons/ti";

// Create an Icons object that contains all icons
export const Icons = {
  ArrowUpRight,
  Info: InfoIcon,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronDown: ChevronDownIcon,
  ChevronRight,
  MoreHorizontal,
  Check: CheckIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  ArrowLeft,
  ArrowRight,
  X: XIcon,
  PanelLeft: PanelLeftIcon,
  ChevronLeft,
  Minus: MinusIcon,
  GripVertical: GripVerticalIcon,
  Bot,
  Database,
  MessageSquare,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  MessageCircle,
  Building,
  Terminal: SquareTerminal,
  Chart: ChartColumn,
  OpenAI: AiOutlineOpenAI,
  XAI: FaXTwitter,
  GoogleCalendar: SiGooglecalendar,
  Contacts: TiContacts,
  Spinner: Loader2,
  Sun: SunMedium,
  Moon,
  Laptop,
  Billing: CreditCard,
  Ellipsis: MoreVertical,
  Add: Plus,
  Warning: HelpCircle,
  User,
  File,
  FileText,
  Image,
  Trash,
  Twitter,
  RefreshCw,
  Txt: PiFileTxt,
  Pdf: PiFilePdf,
  Doc: PiFileDoc,
  Xls: PiFileXls,
  Ppt: PiFilePpt,
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  LogOut,
  Sparkles,
  Key: KeyRound,
  ExternalLink: ExternalLinkIcon,
  CalendarIcon: CalendarIcon,
  XCircle,
  Settings2,
  Loader,
  Upload,
  Copy: CopyIcon,
  Mail: MailIcon,
  CheckCircle,
  RefreshCcw,
  FileUp,
  Download,
  Trash2,
  CheckCircle2,
  Filter,
  Sliders,
  EyeOff,
  ListFilter,
  Text,
  ArrowDownUp,
  ChevronsLeft,
  ChevronsRight,
  CircleDashed,
  CircleOff,
  ArrowUp,
  ArrowDown,
};

// Export individual icons for direct imports
export {
  ArrowUpRight,
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  ChevronRight,
  MoreHorizontal,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  Bot,
  Database,
  MessageSquare,
  MessageCircle,
  Clock,
  Cable,
  Hammer,
  PlusCircle,
  Building,
  ChartColumn as Chart,
};

// Export the React Icons components
export { AiOutlineOpenAI as OpenAI };
export { FaXTwitter as XAI };
